<?php
return [ 

           "TWILIO_ACCOUNT_SID"=>env('TWILIO_ACCOUNT_SID'),
           "TWILIO_API_KEY"=>env('TWILIO_API_KEY'),
           "TWILIO_API_SECRET"=>env('TWILIO_API_SECRET'),
           "TWILIO_CHAT_SERVICE_SID"=>env('TWILIO_CHAT_SERVICE_SID'),
           "TWILIO_NOTIFICATION_SERVICE_SID"=>env('TWILIO_NOTIFICATION_SERVICE_SID'),
           "TWILIO_SYNC_SERVICE_SID"=>env('TWILIO_SYNC_SERVICE_SID')

];